# Shell variables
# Generated by 'wal'
wallpaper="/Users/nichford/.dotfiles/wallpaper/hexfade.jpeg"

# Special
background='#172024'
foreground='#c5c7c8'
cursor='#c5c7c8'

# Colors
color0='#172024'
color1='#c716c3'
color2='#30a7e8'
color3='#ed616f'
color4='#2ccee7'
color5='#ef976f'
color6='#63edbe'
color7='#c5c7c8'
color8='#51575a'
color9='#c716c3'
color10='#30a7e8'
color11='#ed616f'
color12='#2ccee7'
color13='#ef976f'
color14='#63edbe'
color15='#c5c7c8'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
