--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/Users/nichford/.dotfiles/wallpaper/hexfade.jpeg"

-- Special
background="#172024"
foreground="#c5c7c8"
cursor="#c5c7c8"

-- Colors
color0="#172024"
color1="#c716c3"
color2="#30a7e8"
color3="#ed616f"
color4="#2ccee7"
color5="#ef976f"
color6="#63edbe"
color7="#c5c7c8"
color8="#51575a"
color9="#c716c3"
color10="#30a7e8"
color11="#ed616f"
color12="#2ccee7"
color13="#ef976f"
color14="#63edbe"
color15="#c5c7c8"
