# Shell variables
# Generated by 'wal'
wallpaper="/Users/nichford/.dotfiles/wallpaper/springtrain.png"

# Special
background='#0a1d21'
foreground='#cde3e2'
cursor='#cde3e2'

# Colors
color0='#0a1d21'
color1='#ff1969'
color2='#0cfef7'
color3='#08ffe5'
color4='#00f3d4'
color5='#45ffdb'
color6='#5bffe3'
color7='#cde3e2'
color8='#8f9e9e'
color9='#ff1969'
color10='#0cfef7'
color11='#08ffe5'
color12='#00f3d4'
color13='#45ffdb'
color14='#5bffe3'
color15='#cde3e2'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
