--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/Users/nichford/.dotfiles/wallpaper/springtrain.png"

-- Special
background="#0a1d21"
foreground="#cde3e2"
cursor="#cde3e2"

-- Colors
color0="#0a1d21"
color1="#ff1969"
color2="#0cfef7"
color3="#08ffe5"
color4="#00f3d4"
color5="#45ffdb"
color6="#5bffe3"
color7="#cde3e2"
color8="#8f9e9e"
color9="#ff1969"
color10="#0cfef7"
color11="#08ffe5"
color12="#00f3d4"
color13="#45ffdb"
color14="#5bffe3"
color15="#cde3e2"
