#!/usr/bin/env bash

git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
git clone https://github.com/bhilburn/powerlevel9k.git ~/.oh-my-zsh/custom/themes/powerlevel9k
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

# $DOTFILES=~/.dotfiles

# env git clone --depth=1 https://github.com/nickforddesign/dotfiles.git "$DOTFILES"|| {
#   printf "Error: git clone of dotfiles repo failed\n"
#   exit 1
# }

# cd $DOTFILES
