#!/usr/bin/env bash

./scripts/init      # runs bash
./scripts/setup     # runs bash
./scripts/npm       # runs bash, this currently runs asynchronously...
./scripts/link      # runs node
./scripts/source    # runs zsh
