#!/usr/bin/env bash

source ~/.cache/wal/colors.sh

cat > $HOME/.cache/wal/colors-slack.css <<- END
/* MTSlack CSS variables
   Generated by 'wal' */
:root {
  /* Special */
  --bg: $background;
  --fg: $foreground;
  --text: $foreground;

  /* Colors */
  --black: $color0;
  --accent: $color1;
  --accentT: $(echo $color1)70;
  --cyan: $color2;
  --red: $color3;
  --primary: $color4;
  --primaryT: $(echo $color4)70;
  --orange: $color5;
  --green: $color6;
  --silver: $color7;
  --gray: $color8;
  --purple: $color9;
  --blue: $color10;
  --red2: $color11;
  --color12: $color12;
  --color13: $color13;
  --color14: $color14;
  --color15: $color15;
}

END
